language: node_js
node_js:
  - "7"
cache:
  directories:
  - node_modules
before_script:
  - ssh-keygen -t rsa
  - git config --global user.email "krystian.plona@coderslab.pl"
  - git config --global user.name "krystianplona-CL"
  - cp -r Travis_Test/* ./
  - chmod +x bash.sh
before_deploy:
  - openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/<dir> root@185.28.101.228:/root/plona/bash.sh
  on:
    branch: master
addons:
  ssh_known_hosts: root@185.28.101.228
branches:
  only:
    - master
sudo: enabled
dist: trusty
