language: node_js
node_js:
  - "7"
before_script:
  - chmod +x engine.sh
script:
  - './engine.sh'
before_deploy:
  - openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/<dir> root@185.28.101.228:/root/mazurek/test.sh
  on:
    branch: master
addons:
  ssh_known_hosts: root@185.28.101.228
branches:
  only:
    - master
