language: node_js
node_js:
  - "7"
cache:
  directories:
  - node_modules
before_script:
- ssh -l root 185.28.101.228
- git config --global user.email "krystian.plona@coderslab.pl"
- git config --global user.name "krystianplona-CL"
- git clone git@github.com:krystianplona-CL/Travis_Test.git
- cp -r Travis_Test/* ./
- ssh -l root 185.28.101.228
- chmod +x bash.sh
script:
- "./bash.sh"
after_success:
- "./tagCheck.sh"
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- "./push.sh;"
- curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install |
  bash
- artifacts upload --s3-region="eu-west-1" --target-paths="krystianplona-CL/Travis_Test/$(cat
  lastTag)"
sudo: enabled
dist: trusty
